### ISSUE TITLE
Pydantic BaseSettings vs Starlette Config

### ISSUE THREAD

**Issue by hackwithharsha** [aaronbassett/FARM-starter#1]
Hi Aaron,

Thanks for the demo,  I have some question about config module..

```python
from pydantic import BaseSettings


class CommonSettings(BaseSettings):
    APP_NAME: str = "FARM Starter"
    DEBUG_MODE: bool = False


class ServerSettings(BaseSettings):
    HOST: str = "0.0.0.0"
    PORT: int = 8000


class DatabaseSettings(BaseSettings):
    DB_URL: str
    DB_NAME: str


class Settings(CommonSettings, ServerSettings, DatabaseSettings):
    pass


settings = Settings()
```

Do you recommend this approach in production applications, as this `Settings()` is instantiated every time when I import the config module in larger applications when we have multiple route files. Please share your opinion !!

**Comment by sergio-chumacero** [comment]
From the [Python docs](https://docs.python.org/3/tutorial/modules.html):

>  For efficiency reasons, each module is only imported once per interpreter session.

So you don't have to worry about `Settings()` being instantiated with each import.

Both Starlette Config and Pydantic Base Settings will get the job done. The benefits of using Pydantic BaseSettings over Starlette Config imo is that you can use the type casting and validation that you already use, instead of needing to learn how Starlette data structures work.

**Comment by hackwithharsha** [comment]
Thank you, that helps
